project/project/urls.py
# from django.contrib import admin
from django.urls import path
from project.controllers import site, start, place, service

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', site.login),
    path('login/', site.login),
    path('login/<int:code>/', site.login),
    path('logout/', site.logout),
    path('signup/', site.signup),
    path('index/', site.index),
    path('plans/', site.plans),
    path('manage/', site.manage),
    path('place/', place.place),
    path('service/<int:pk>/', place.service),
    path('start/run/', start.run),
    path('place/<int:pk>/', place.detail),
    path('get_place/<int:pk>/', place.get_data),
    path('service/request/<int:pk>/', service.request_service),
    path('service/add/', service.add_service),
    path('service/get_order/<int:pk>/', service.get_order),
    path('service/change_state/<int:pk>/<int:status>/', service.change_state),
    path('service/record/', service.record),
    path('service/record/<int:pk>/', service.record),
    path('service/get_record/<int:pk>/', service.get_records),
]

project/project/models.py
from django.db import models

class Rol(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class User_College(models.Model):
    name = models.CharField(max_length=40)
    identification = models.CharField(max_length=11)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=10)
    password = models.CharField(max_length=200)
    rol = models.ForeignKey(
        Rol, on_delete=models.CASCADE
    )
    state = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Type_Place(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Place(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    type_place = models.ForeignKey(
        Type_Place, on_delete=models.CASCADE
    )
    state = models.BooleanField(default=True)

    def __str__(self):
        return self.name

def place_directory_path(instance, filename):
    return 'static/upload/place/{0}/{1}'.format(instance.place.id, filename)

class Image_Place(models.Model):
    place = models.ForeignKey(
        Place, on_delete=models.CASCADE
    )
    image = models.FileField(upload_to=place_directory_path, null=True, blank=True)
    location = models.IntegerField()
    state = models.BooleanField(default=True)

    def __str__(self):
        return self.location

class User_Place(models.Model):
    user_college = models.ForeignKey(
        User_College, on_delete=models.CASCADE
    )
    place = models.ForeignKey(
        Place, on_delete=models.CASCADE
    )
    state = models.BooleanField(default=True)

    def __str__(self):
        return self.id

class Type_Service(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Service(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)
    type_service = models.ForeignKey(
        Type_Service, on_delete=models.CASCADE
    )
    state = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Line_Day(models.Model):
    day = models.IntegerField()
    start_hour = models.TimeField()
    end_hour = models.TimeField()

    def __str__(self):
        return self.day

class Schedule_Service(models.Model):
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE
    )
    line_day = models.ForeignKey(
        Line_Day, on_delete=models.CASCADE
    )
    state = models.BooleanField(default=True)

    def __str__(self):
        return self.id

class Service_Place(models.Model):
    place = models.ForeignKey(
        Place, on_delete=models.CASCADE
    )
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE
    )
    state = models.BooleanField(default=True)

    def __str__(self):
        return self.id

def catalog_directory_path(instance, filename):
    return 'static/upload/service/{0}/catalog/{1}'.format(instance.service.id, filename)

class Catalog_Service(models.Model):
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE
    )
    name = models.CharField(max_length=30)
    description = models.CharField(max_length=200)
    cost = models.IntegerField()
    image = models.FileField(upload_to=catalog_directory_path, null=True, blank=True)
    state = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Order_Service(models.Model):
    user_college = models.ForeignKey(
        User_College, on_delete=models.CASCADE
    )
    date = models.DateField(auto_now_add=True)
    status = models.IntegerField()

    def __str__(self):
        return self.date

class Order_Catalog(models.Model):
    order_service = models.ForeignKey(
        Order_Service, on_delete=models.CASCADE, null=True
    )
    catalog_service = models.ForeignKey(
        Catalog_Service, on_delete=models.CASCADE
    )
    quantity = models.IntegerField()

    def __str__(self):
        return self.id

class Traceability_Order_Service(models.Model):
    order_service = models.ForeignKey(
        Order_Service, on_delete=models.CASCADE, null=True
    )
    date_time = models.DateTimeField(auto_now_add=True)
    action = models.CharField(max_length=30)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.action

class Fines(models.Model):
    user_college = models.ForeignKey(
        User_College, on_delete=models.CASCADE
    )
    service = models.ForeignKey(
        Service, on_delete=models.CASCADE
    )
    date_time = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField()

    def __str__(self):
        return self.date_time

project/project/controllers/place.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponseRedirect
from project.models import (
    Catalog_Service,
    Image_Place,
    Line_Day,
    Place,
    Service,
    Service_Place,
    Schedule_Service,
    User_Place,
    Order_Catalog,
    Order_Service,
)
from datetime import date
import pusher


def place(request):
    if 'user' in request.session:
        if request.session['user']['rol'] == 2:
            response = {}
            response['session'] = request.session['user']

            try:
                if request.method == "POST":
                    data = request.POST
                    # print('data:::::::::::::::::')
                    # print(data)
                    line_day_val = Line_Day()
                    line_day_val.day = data['day']
                    line_day_val.start_hour = data['start']
                    line_day_val.end_hour = data['end']
                    line_day_val.save()
                    # Relación Horario y el Servicio
                    if data['id'] != '':
                        schedule_service_val = Schedule_Service.objects.get(id=data['id'], service_id=data['service'])
                        schedule_service_val.line_day = line_day_val
                        schedule_service_val.state = True
                        schedule_service_val.save()
                    else:
                        schedule_service_val = Schedule_Service()
                        schedule_service_val.line_day = line_day_val
                        schedule_service_val.service_id = data['service']
                        schedule_service_val.save()

                    return HttpResponseRedirect('/place/')

                user_place_val = User_Place.objects.get(user_college_id=request.session['user']['id'])
                place_val = Place.objects.get(id=user_place_val.place_id)

                services_data = []
                service_place_values = Service_Place.objects.filter(place=place_val)
                for service_place_val in service_place_values:

                    schedule_data = []
                    use_array = []
                    schedule_service_values = Schedule_Service.objects.filter(service_id=service_place_val.service_id, state=True)
                    for schedule_service_val in schedule_service_values:
                        day_array = ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']
                        use_array.append(schedule_service_val.line_day.day)

                        schedule_data.append({
                            'id': schedule_service_val.id,
                            'day': schedule_service_val.line_day.day,
                            'day_name': day_array[schedule_service_val.line_day.day-1],
                            'start': schedule_service_val.line_day.start_hour,
                            'end': schedule_service_val.line_day.end_hour,
                        })
                    services_data.append({
                        'id': service_place_val.service_id,
                        'name': service_place_val.service.name,
                        'description': service_place_val.service.description,
                        'schedule': schedule_data,
                        'use_array': use_array,
                    })

                # print('services_data')
                # print(services_data)

                data_place = {
                    'name': place_val.name,
                    'description': place_val.description,
                    'type': place_val.type_place.name,
                    'services': services_data,
                }
                response['data'] = data_place

                return render(request, 'place/place.html', context=response)
            except User_Place.DoesNotExist:
                pass
            except Place.DoesNotExist:
                pass
        return HttpResponseRedirect('/index/')
    else:
        return HttpResponseRedirect('/login/')

def detail(request, pk):
    if 'user' in request.session:
        response = {}
        response['session'] = request.session['user']
        
        try:
            place_val = Place.objects.get(id=pk)
            services_data = []
            service_place_values = Service_Place.objects.filter(place=place_val)
            for service_place_val in service_place_values:

                schedule_data = []
                schedule_service_values = Schedule_Service.objects.filter(service_id=service_place_val.service_id)
                for schedule_service_val in schedule_service_values:
                    schedule_data.append({
                        'day': schedule_service_val.line_day.day,
                        'start': schedule_service_val.line_day.start_hour,
                        'end': schedule_service_val.line_day.end_hour,
                    })
                services_data.append({
                    'id': service_place_val.service_id,
                    'name': service_place_val.service.name,
                    'description': service_place_val.service.description,
                    'schedule': schedule_data,
                })

            # print('services_data')
            # print(services_data)

            data_place = {
                'name': place_val.name,
                'description': place_val.description,
                'type': place_val.type_place.type,
                'services': services_data,
            }
            response['data'] = data_place
        except Place.DoesNotExist:
            return redirect('/plans/')
        return render(request, 'place/detail.html', context=response)
    else:
        return HttpResponseRedirect('/login/')

def get_data(request, pk):
    data_place = {}
    try:
        place_val = Place.objects.get(id=pk)
        image = ''
        image_val = Image_Place.objects.filter(place=place_val)
        if image_val:
            image = str(image_val[0].image)


        services_data = []
        service_place_values = Service_Place.objects.filter(place=place_val)
        for service_place_val in service_place_values:

            schedule_data = []
            schedule_service_values = Schedule_Service.objects.filter(service_id=service_place_val.service_id)
            for schedule_service_val in schedule_service_values:
                schedule_data.append({
                    'day': schedule_service_val.line_day.day,
                    'start': schedule_service_val.line_day.start_hour,
                    'end': schedule_service_val.line_day.end_hour,
                })
            services_data.append({
                'id': service_place_val.service_id,
                'name': service_place_val.service.name,
                'description': service_place_val.service.description,
                'schedule': schedule_data,
            })

        data_place = {
            'id': place_val.id,
            'name': place_val.name,
            'description': place_val.description,
            'type': place_val.type_place.id,
            'image': image,
            'services': services_data,
        }
    except Place.DoesNotExist:
        pass
    return JsonResponse(data_place)

def service(request, pk):
    if 'user' in request.session:
        response = {}
        response['session'] = request.session['user']
        
        try:
            catalog_list = []
            service_val = Service.objects.get(id=pk)
            catalog_values = Catalog_Service.objects.filter(service=service_val, state=True)
            for catalog in catalog_values:
                catalog_list.append(catalog.id)
            order_values = Order_Catalog.objects.filter(catalog_service_id__in=catalog_list)
            
            order_list = []
            for order in order_values:
                order_list.append(order.order_service_id)
            today = date.today()
            order_service_values = Order_Service.objects.filter(id__in=order_list, status=1, date=today)
            accepted_service_values = Order_Service.objects.filter(id__in=order_list, status__in=[2,4], date=today)

            data_service = {
                'id': service_val.id,
                'name': service_val.name,
                'description': service_val.description,
                'catalogs': catalog_values,
                'orders': order_service_values,
                'accepted': accepted_service_values,
            }
            response['data'] = data_service
            return render(request, 'place/service.html', context=response)
        except Service.DoesNotExist:
            pass
        return HttpResponseRedirect('/index/')
    else:
        return HttpResponseRedirect('/login/')

project/project/templates/service/record.html
{% extends "layout.html" %}
{% load static %}

{% block head %}
<!-- ESTILOS DEL CSS -->
<link rel="stylesheet" href="{% static 'vendors/jvectormap/jquery-jvectormap.css' %}">
<link rel="stylesheet" href="{% static 'vendors/map/style.css' %}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
<style>
  .modal {
    max-width: 650px;
  }
</style>
{% endblock %}
{% block main %} 

<div class="page-wrapper mdc-toolbar-fixed-adjust">
  <div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
      <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop mdc-layout-grid__cell--span-12-tablet">
        <div class="table-responsive">
          <div class="mdc-card info-card info-card--success">
            <div class="card-inner">
              <h5 class="card-title">Historial</h5>
            </div>
            <table class="table table-hoverable">
              <thead>
                <tr>
                  <th>
                    {% if pk != None %}
                      Usuario
                    {% else %}
                      Servicio
                    {% endif %}
                  </th>
                  <th>Fecha</th>
                  <th>Estado</th>
                  <th>Detalle</th>
                </tr>
              </thead>
              <tbody id="list_accept_order">
                {% for order in orders %}
                <tr id="order_{{ order.id }}">
                  <td>
                    {% if pk != None %}
                      {{ order.name }}
                    {% else %}
                      {{ order.service }}
                    {% endif %}
                  </td>
                  <td>{{ order.date|date:'Y-m-d' }}</td>
                  <td>
                    {% if order.status == 1 %}
                      Creado
                    {% elif order.status == 2 %}
                      Aceptado
                    {% elif order.status == 3 %}
                      Rechazado
                    {% elif order.status == 4 %}
                      Listo
                    {% elif order.status == 5 %}
                      Entregado
                    {% endif %}
                  </td>
                  <td><button order_id="{{ order.id }}"
                    class="mdc-button mdc-ripple-upgraded outlined-button--primary see_traza_order">Ver</button></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="order_traza" class="modal">
  <div class="mdc-card">
    <div class="mdc-layout-grid">
      <div class="mdc-layout-grid__inner">
        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop">
          <h3>Detalles</h3>
        </div>
        <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop mdc-layout-grid__cell--span-12-tablet">
          <div class="table-responsive">
            <div class="mdc-card info-card info-card--success">
              <table class="table table-hoverable">
                <thead>
                  <tr>
                    <th class="text-left">Producto</th>
                    <th>Cantidad</th>
                    <th>Total</th>
                  </tr>
                </thead>
                <tbody id="list_catalog_order">
                  
                </tbody>
              </table>
              <div>
                <h5 style="float: right;" class="card-padding font-weight-light pb-2 mb-1">Total <b id="total_order">$0</b></h5>
              </div>
              <br>
              
              <div class="card-inner">
                <h5 class="card-title">Trazabilidad</h5>
              </div>
              <table class="table table-hoverable">
                <thead>
                  <tr>
                    <th>Detalle</th>
                    <th>Fecha</th>
                  </tr>
                </thead>
                <tbody id="list_traza_order">
                  
                </tbody>
              </table>

              <div class="card-inner" id="multa">
                <h5 style="color: red; float: right;" class="card-padding font-weight-light pb-2 mb-1">Tienes una Multa de: <b id="total_multa">$0</b></h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block js %} 
<!-- CODIGO JAVASCRIPT -->
<script src="{% static 'vendors/jvectormap/jquery-jvectormap.min.js' %}"></script>
<script src="{% static 'vendors/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<script src="{% static 'js/dashboard.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>

<script>
  $(document).ready(function() {

    $('.see_traza_order').click(function(){
      
      $('#list_catalog_order').html('');
      $('#list_traza_order').html('');

      var order_select = $(this).attr('order_id');
      $.ajax({
        type: "GET",
        url: "/service/get_order/" + order_select + "/",
        success: function(data) {
          data.catalogs.forEach(catalog => {
            var content = '<tr><td>' + catalog.name + '</td><td>' + catalog.quantity + '</td><td>$' + catalog.total + '</td></tr>';
            $('#list_catalog_order').append(content);
          });
          $('#total_order').text('$'+ data.total);

          if (data.multa != 0) {
            $('#multa').css('display', 'block');
            $('#total_multa').text('$'+ data.multa);
          } else {
            $('#multa').css('display', 'none');
          }

        }
      });

      $.ajax({
        type: "GET",
        url: "/service/get_record/" + order_select + "/",
        success: function(data) {
          data.traza_data.forEach(traza => {
            var d = new Date(traza.date);
            var datestring = d.getFullYear() + "-" + (d.getMonth()+1) + "-" + d.getDate() + " " +
              d.getHours() + ":" + d.getMinutes();
            var content = '<tr><td>' + traza.description + '</td><td>' + datestring + '</td></tr>';
            $('#list_traza_order').append(content);
          });
          $('#order_traza').modal();
        }
      });

    });

  });

</script>

{% endblock %}

project/project/templates/service/request.html
{% extends "layout.html" %}
{% load static %}

{% block head %}
<!-- ESTILOS DEL CSS -->
<link rel="stylesheet" href="{% static 'vendors/jvectormap/jquery-jvectormap.css' %}">
<link rel="stylesheet" href="{% static 'vendors/map/style.css' %}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
{% endblock %}
{% block main %} 
<!-- TODO DEL HTML -->

<div class="page-wrapper mdc-toolbar-fixed-adjust">
  <div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
      <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
        <div class="mdc-card">
          <div class="d-block d-sm-flex justify-content-between align-items-center mt-2">
            <div class="dx-viewport">
              <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
                <div class="mdc-card p-0">
                  <h6 class="card-title card-padding pb-0">{{ data.name }}</h6>
                  <h5 class="card-padding font-weight-light pb-2 mb-1">{{ data.description }}</h5>
                </div>
              </div>
            </div>
          </div>
        </div> 
      </div>
    </div>
  </div> 
</div>


<div class="page-wrapper mdc-toolbar-fixed-adjust">
  <div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
      {% for catalog in data.catalogs %}
      <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-4-desktop mdc-layout-grid__cell--span-4-tablet">
        <div class="mdc-card info-card info-card--success">
          <div class="card-inner">
            <h5 class="card-title">{{ catalog.name }}</h5>
            <h5 class="font-weight-light pb-2 mb-1 border-bottom">${{ catalog.cost }}</h5>
            <img style="width: 100%;" src="/static/{{ catalog.image }}" alt="">
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

<div class="page-wrapper mdc-toolbar-fixed-adjust">
  <div class="mdc-layout-grid">
    <div class="mdc-layout-grid__inner">
      <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12-desktop mdc-layout-grid__cell--span-12-tablet">
        <div class="table-responsive">
          <div class="mdc-card info-card info-card--success">
            <div class="card-inner">
              <h5 class="card-title">Solicitar Servicio</h5>
            </div>
            <div>
              <div class="mdc-layout-grid">
                <div class="mdc-layout-grid__inner">
                  <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-4">
                    <div class="mdc-text-field w-100">
                      <select name="catalog" class="mdc-text-field__input" style="height: 110%;" id="catalog_service" required>
                        {% for catalog in data.catalogs %}
                        <option cost="{{ catalog.cost }}" value="{{ catalog.id }}">{{ catalog.name }}</option>
                        {% endfor %}
                      </select>
                      <div class="mdc-line-ripple"></div>
                      <label for="text-field-hero-input" class="mdc-floating-label">Producto</label>
                    </div>
                  </div>
                  <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-4">
                    <div class="mdc-text-field w-100">
                      <input name="num" type="number" min="0" max="20" autocomplete="off" class="mdc-text-field__input" id="num_service" required>
                      <div class="mdc-line-ripple"></div>
                      <label for="text-field-hero-input" class="mdc-floating-label">Cantidad</label>
                    </div>
                  </div>
                  <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-4">
                    <button id="add_catalog" class="mdc-button mdc-button--raised w-100">Añadir</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="mdc-card info-card info-card--success">
            <div class="table-responsive">
              <div class="mdc-card info-card info-card--success">
                <table class="table table-hoverable">
                  <thead>
                    <tr>
                      <th>Producto</th>
                      <th>Cantidad</th>
                      <th>Total</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody id="list_catalog">
                  </tbody>
                </table>
                <div>
                  <h5 style="float: right;" class="card-padding font-weight-light pb-2 mb-1">Total <b id="total_service">$0</b></h5>
                </div>
              </div>
            </div>
                
            <div class="mdc-layout-grid">
              <div class="mdc-layout-grid__inner">
                <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                  <button id="cancel_service" class="mdc-button mdc-button--danger w-100">Cancelar</button>
                </div>
                <div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-6">
                  <button id="add_service" class="mdc-button mdc-button--success w-100">Solicitar</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block js %} 
<!-- CODIGO JAVASCRIPT -->
<script src="{% static 'vendors/jvectormap/jquery-jvectormap.min.js' %}"></script>
<script src="{% static 'vendors/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<script src="{% static 'js/dashboard.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>

<script>
  $(document).ready(function() {

    var catalog_service = [];

    $('#add_catalog').click(function(){
      var id = $('#catalog_service').val();
      var name = $('#catalog_service').children("option:selected").text();
      var cost = $('#catalog_service').children("option:selected").attr('cost');
      var num = $('#num_service').val();
      var total = num * cost;
      
      if (num != '' && num > 0 && num < 21) {
        var content = '<tr><td>' + name + '</td><td>' + num + '</td><td>$' + total + '</td><td></td></tr>';
        $('#list_catalog').append(content);
        
        catalog_service.push({
          'id': id,
          'num': num,
          'total': total,
        });

        var total_service = 0;
        catalog_service.forEach(element => {
          total_service += element.total;
        });
        $('#total_service').text('$'+ total_service);
      } else {
        swal({
          title: "Servicio",
          text: 'Cantidad invalida',
          icon: "warning",
        });
      }

      // var service = $(this).attr('service_id');


      // $('#id_service').val(service);

      // $('#id_schedule').val('');
      // $('#day_schedule').val('');
      // $('#start_schedule').val('');
      // $('#end_schedule').val('');
      // $('#ex1').modal();
    });
      
    $('#cancel_service').click(function(){
      $('#list_catalog').html('');
      catalog_service = [];
      $('#total_service').text('$0');
    });

    $('#add_service').click(function(){
      if (catalog_service.length > 0) {
        $.ajax({
          type: "POST",
          url: "/service/add/",
          data: {
            'catalog': JSON.stringify(catalog_service)
          },
          success:function(data){
              console.log('data')
              console.log(data)
              if (data['status'] == 'success') {
                $('#list_catalog').html('');
                catalog_service = [];
                $('#total_service').text('$0');
                swal({
                  title: "Servicio",
                  text: 'Se ha realizado el pedido correctamente!',
                  icon: "success",
                });
              } else {
                swal({
                  title: "Servicio",
                  text: 'No hay disponibilidad en este horario!',
                  icon: "error",
                });
              }
          },
        });
      } else {
        swal({
          title: "Servicio",
          text: 'Debes añadir un producto!',
          icon: "warning",
        });
      }
    });

  });

</script>

{% endblock %}